---
matrix:
  include:
    - IMAGE: 3.6-stretch
      TOXENV: py36
    - IMAGE: 3.7-stretch
      TOXENV: py37
    - IMAGE: 3.8-buster
      TOXENV: py38
    - IMAGE: 3.8-buster
      TOXENV: lint
    - IMAGE: 3.8-buster
      TOXENV: sort
    - IMAGE: 3.8-buster
      TOXENV: format
    - IMAGE: 3.8-buster
      TOXENV: type
    - IMAGE: 3.8-buster
      TOXENV: docs
    - IMAGE: 3.8-buster
      TOXENV: metadata-release

pipeline:
  build:
    image: python:${IMAGE}
    commands:
      - pip install tox==3.14.6
      - tox -e ${TOXENV}
